export const REFACTORING_HOME_URL = 'https://refactoring.fm/'
export const BIBLIO_PRODUCT_BOARD_URL = 'https://biblio.canny.io/'
export const BIBLIO_GITHUB_DISCUSSIONS_URL = 'https://github.com/refactoringhq/biblio/discussions'
export const BIBLIO_GITHUB_CONTRIBUTING_URL = 'https://github.com/refactoringhq/biblio/blob/main/CONTRIBUTING.md'
export const BIBLIO_GITHUB_ISSUES_URL = 'https://github.com/refactoringhq/biblio/issues'
export const BIBLIO_GITHUB_PULL_REQUESTS_URL = 'https://github.com/refactoringhq/biblio/pulls'
